package com.betherichest.android;

public enum StatType {
    TOTAL_MONEY_COLLECTED,
    TOTAL_CLICKS,
    TOTAL_PLAYING_TIME,
    TOTAL_MONEY_FROM_CLICKS,
    MONEY_SPENT,
    TOTAL_GAMBLING,
    GAMBLING_WINS,
    GAMBLING_LOSES,
    MONEY_FROM_GAMBLING,
    MONEY_SPENT_ON_GAMBLING,
    GAMBLING_BALANCE,
    TOTAL_INVESTMENT_LEVELS,
    UPGRADES_BOUGHT,
    FIRST_DOLLAR,
    HIGHEST_MONEY,
    VIDEOS_WATCHED,
    MONEY_FROM_VIDEOS,
    UNLOCKED_ACHIEVEMENTS,
}
